version: '2'

services:  
  
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./local/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/snippets:/nginx/snippets
      - ~/vhosts:/vhosts   
    logging:
      driver: "json-file"

  fpm:
    image: masterforweb/php-fpm-plus
    restart: always
    volumes:  
      - ~/vhosts:/vhosts 

  mysql:
    image: mariadb:latest
    restart: always
    env_file: 
      - ./env/mysql.env
    volumes:  
      - data:/var/lib/mysql 
      - ~/backup:/var/backup
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - 8181:80
    volumes:
     - /sessions
    environment: 
      PMA_ARBITRARY: 1
    logging:
      driver: "none"             
      
volumes:
  data:
    driver: local                
       
 
